### PR TITLE
Can specify complete sqlite3 open flags in connection parameters

### PR DESCRIPTION
**Pull request by Cavaler**
For example can be used to open database read-only

### CODE REVIEW

**Comment by vadz** [comment]
I'm not sure that passing numeric flags value is really a good way to do things. Wouldn't it be better to add `readonly` parameter instead?

Also, whicheever solution is chosen it really ought to be mentioned in `docs/backend/sqlite3.md`, could you please update that file as well?

**Comment by Cavaler** [comment]
For the sole purpose of 'readonly' - yes, a separate keyword could be used. But there are a lot of other flags SQLite3 supports, and adding separate keyword for every one is not practical in my opinion.

**Comment by Cavaler** [comment]
I added separate 'readonly' flag, and updated description

**Comment by vadz** [comment]
Thanks for the update! I'll merge `readonly` addition, but more I think about it, less I like the idea of specifying numeric flags as strings. This is fragile (too easy to make a mistake), inconsistent with the other backends and it's not clear at all how does it work in conjunction with the other connection string parameters. So I'm afraid I won't merge this part, sorry.

**Comment by Cavaler** [comment]
> but more I think about it, less I like the idea of specifying numeric flags as strings. This is fragile (too easy to make a mistake), inconsistent with the other backends and it's not clear at all how does it work in conjunction with the other connection string parameters.

Well actually there is already one similar parameter, 'timeout', and it works quite well. So 'flags' wouldn't be any different.

**Comment by vadz** [comment]
Err, no, it's not similar at all. Timeout is a number, not a combination of masks. Specifying a number as string is perhaps not ideal, but there is no danger of confusion, hardcoding accidentally wrong value nor any doubt about how does it interact with the other flags.

What problem are you trying to solve here, exactly? I.e. why do you need to pass numeric flags?

**Pull request closed without merging**
