### PR TITLE
Improve error message when an odbc error occurs

### LINKED ISSUE #228: odbc_soci_error should append sqlstate_, sqlcode_ and message_ to the string used to initialize soci_error
Otherwise you get a near-useless message from std::exception::what() - something like "Error Connecting to database".

The db2 backend has a better implementation.

### PR DESCRIPTION
**Pull request by lukeocamden**
Improve error message when an odbc error occurs

Fixes #228

### CODE REVIEW

**Comment by shearer** [comment]
How is the status of this pull request? I think an improved error message in case of an odbc error is very interesting.
Or were there other modifications in the actual version for error messaging?

**Comment by mloskot** [comment]
@shearer  I've got stuck with bugfix release 3.2.3, so hasn't got time to clear PRs against develop (aka SOCI 4). I'll try to clear it soon.

**Comment by shearer** [comment]
@mloskot: Many thanks for the fast reply. Will there be any odbc error message improvements in 3.2.3? Happy, when this PR will be implemented in SOCI 4. Best Wishes!

**Comment by mloskot** [comment]
@shearer It's not a large changeset and I think it can be considered as a fix-kind-of improvement. I've marked it for 3.2.3 and will see if I can incorporate it there without issues.

**Comment by shearer** [comment]
Many thank again!

**Comment by vadz** [comment]
I plan to work on this, as part of general improvement to SOCI error messages (see also #138), soon, but I'll be only making changes on the `develop` branch.

**Pull request closed without merging**
