### PR TITLE
Fix issue SOCI/soci#370

### PR DESCRIPTION
**Pull request by musopr**
Okay, here it is.

### CODE REVIEW

**Comment by vadz** [comment]
I'm not sure when did this header appear, but it's pretty old, I see that it already was in 1.47 and it's only absent from the very ancient 1.33, so I guess it should be fine.

What is the current Boost version requirement in SOCI anyhow?

**Comment by musopr** [comment]
I was trying to find that out. I only thing I've seen so far is that at least version 1.35 is needed for boost::fusion::vector support, mentioned on the [Integration with Boost](http://soci.sourceforge.net/doc/3.2/boost.html) page.

**Comment by musopr** [comment]
I could do a conditional include for Boost versions >= 1.58, since this is the latest version to throw an error.

**Comment by snikulov** [comment]
@musopr already on master with 063e7537403fc609d042824102df1550f27691a2

**Pull request closed without merging**
