### PR TITLE
Convert the tests to use CATCH with minimal changes.

### PR DESCRIPTION
**Pull request by vadz**
This is not supposed to be merged yet as the changes are not finished.

Comments about them are already welcome though.

### CODE REVIEW

**Comment by mloskot** [comment]
Responded with my comments in the thread [RFD: Using CATCH for tests](http://sourceforge.net/p/soci/mailman/message/33640616/)

**Comment by vadz** [comment]
I think this can be merged now. A lot of things could be improved and I'll try to do at least some of them in the future commits, but for now I'd like to add more tests and this means committing this first.

**Comment by mloskot** [comment]
:+1:

**Comment by vadz** [comment]
Merged now.

**Pull request closed without merging**
