### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by snikulov**
Use table with build statuses for branches (master and release/3.2)
We also can put appveyor.yml on release/3.2 and then update readme with build status for that branch.

### CODE REVIEW

**Comment by mloskot** [comment]
@snikulov Good idea. Feel free to enable Appveyor for release/3.2.

However, if it's too much hassle, I would not waste time on release/3.2.
As per explanation on https://github.com/SOCI/soci/wiki/Branches, it is not actively maintained, no further 3.x release are planned or promised.

**Comment by snikulov** [comment]
@mloskot Ok. But if we have no exact plans for 4.0.0 release date, 3.2.x still the best stable release, I suspect.

**Comment by mloskot** [comment]
It depends. I'd say this way:
* master (SOCI 4): we keep it healthy and usable, so consider it as a **failry stable rolling release**, though we haven't published it officially as packaged release.
* release/3.2: is stable, but it is becoming **deprecated**, so due to lack of manpower, we are not actively working on it anymore, so we encourage people to switch to the master now - it would also help to test it and stabilise it faster

**Comment by snikulov** [comment]
@mloskot no problem. Can we close #379 since it is not exactly true? 
We can see that "Build VS2015" successful and no more response from submitter available?

**Comment by mloskot** [comment]
Closed. Thx

**Pull request merged**
