### PR TITLE
fix clang build warning, fix cmake generated file that is not ignored

### PR DESCRIPTION
**Pull request by jeking3**

### CODE REVIEW

**Comment by snikulov** [comment]
:-1: I see no reason to merge TODO into source.

**Comment by mloskot** [comment]
Instead it would be better to fix it straight away.

**Comment by mloskot** [comment]
Closing as it is better to fix it properly, see #412

**Comment by jeking3** [comment]
There was already a TODO in the code to remove those methods.  Given it was allowed before, I figured I would submit my workaround that will allow clang users to make forward progress.  In any case, I'll use this workaround locally while I tackle more important things.  I don't know where the SOCI bug database is, but this needs to be entered into the bug database so someone more familiar with the project can fix the infrastructure here.  It is not a trivial change.

**Comment by mloskot** [comment]
@jeking3 There is nothing with TODOs in the code. We just think it is unnecessary to add new ones via PRs (notice, those existing TODOs have been there for long time, too long).

SOCI bug database is here. We use [GitHub Issues](https://guides.github.com/features/issues/) as a bug database. So, I have created bug entry in #412.

**Comment by snikulov** [comment]
@jeking3 Simple workaround for clang is remove -Werror from SociConfig.cmake 
HTH.

**Pull request closed without merging**
