### PR TITLE
fix for #369

### LINKED ISSUE #369: Building of very first file fails with mingw
With the most recent master checkout (70085e8a0a6d0d) building with mingw fails now at the very first file. 
Although I already got one ticket ( #338 ) about building problems with mingw, I have opened this one, because I assume this is just a minor, different, one line correction bug.
```
C:\Users\klm\Downloads\soci_build>"C:\Program Files (x86)\Dev-Cpp\MinGW64\bin\mi
ngw32-make.exe"
Scanning dependencies of target soci_core
[  1%] Building CXX object src/core/CMakeFiles/soci_core.dir/backend-loader.cpp.
obj
C:\Users\klm\Downloads\soci\src\core\backend-loader.cpp:1:0: error: -fPIC ignore
d for target (all code is position independent) [-Werror]
 //
 ^
cc1plus.exe: all warnings being treated as errors
src\core\CMakeFiles\soci_core.dir\build.make:54: recipe for target 'src/core/CMa
keFiles/soci_core.dir/backend-loader.cpp.obj' failed
mingw32-make[2]: *** [src/core/CMakeFiles/soci_core.dir/backend-loader.cpp.obj]
Error 1
CMakeFiles\Makefile2:125: recipe for target 'src/core/CMakeFiles/soci_core.dir/a
ll' failed
mingw32-make[1]: *** [src/core/CMakeFiles/soci_core.dir/all] Error 2
Makefile:126: recipe for target 'all' failed
mingw32-make: *** [all] Error 2
```

### PR DESCRIPTION
**Pull request by snikulov**
Hello all,

I've make some changes to fix #369 
 
- updates to find odbc
- remove mingw from #if
- fixed include for boost::optional (according changes in 1.58 https://svn.boost.org/trac/boost/ticket/10825)
- picked up latest Catch UT framework to work with mingw

### CODE REVIEW

**Comment by vadz** [comment]
Thanks, but it would be great if you could please split the unrelated fixes in separate commits.

Also, Travis failures need to be fixed, of course.

**Comment by snikulov** [comment]
@vadz it's all related.

**Comment by vadz** [comment]
Err, this really doesn't seem to be the case. ODBC, MinGW and boost::optional are 3 totally different fixes AFAICS. Why can't they be committed individually?

**Comment by snikulov** [comment]
@vadz Well. I see no reason for that, because it targets same issue. But if you insist I will spend some time to split it.

**Comment by vadz** [comment]
Atomic commits are preferable because they can be reviewed, applied, merged and reverted independently. They also make exploring the history or bisecting it in order to find bugs much more convenient. So yes, IMO it would certainly be preferable to have them.

**Comment by snikulov** [comment]
@vadz ok. no problem. will do.

**Pull request closed without merging**
