### PR TITLE
mingw: not use ms extension for MinGW G++ compilation

### PR DESCRIPTION
**Pull request by snikulov**
Fixed warnings on MinGW compilation (now all compilers in both CI are green).

@vadz Could you please review and comment?

### CODE REVIEW

**Comment by mloskot** [comment]
Since this touches CMake, and @vadz prefers to not to touch CMake ;-), I'll join the review: looks good to me

**Comment by snikulov** [comment]
@mloskot at least now builds are green. Need to integrate build with Boost and put tests into play.

**Comment by mloskot** [comment]
Good. I'll take the liberty and merge it. Hopefully, @vadz will agree.

**Comment by vadz** [comment]
Yes, absolutely, thank you.

**Pull request merged**
