### PR TITLE
AppVeyor: enable MSSQL ODBC connection

### PR DESCRIPTION
**Pull request by snikulov**
Enabled MSSQL tests.
Some code modification in tests was introduced.
@vadz @mloskot Could you please review?

### CODE REVIEW

**Comment by snikulov** [comment]
@vadz BTW, here the exposure for #287 and #383. Test was failed on nvarchar.
I believe it related to http://stackoverflow.com/questions/10025032/what-is-the-meaning-of-the-prefix-n-in-t-sql-statements 
One of idea how to fix it - is use N'< here the long string >'

**Comment by vadz** [comment]
Sorry, I'm really not sure what is the idea here: why do we need to create a new database just for MS SQL and just for this test? And why do we need yet another helper class, could we reuse `test_context_base` for this instead?

**Comment by snikulov** [comment]
@vadz Because I'm limited with CI environment. It is not my or your local PC. 
For PostgreSQL I can create database before test run from cmd console.
With MSSQL I don't know how to do this. So I prepare environment inside the test.

If you provide guideline how to reuse test_context_base and reuse same approach approach for "// MS SQL-specific tests" I'll change my code per your suggestion.

**Comment by snikulov** [comment]
@vadz Personally, I use fixtures for that. But didn't see same approach anywhere in test code.

**Comment by vadz** [comment]
Normally [sqlcmd.exe](https://msdn.microsoft.com/en-us/library/ms162773.aspx) should be available in the MS SQL installation, so it should be possible to use it to create the test database and avoid doing it in the code entirely.

But maybe creating the database from the code is actually better, it's just that I don't like the inconsistency of doing it just for MS SQL but not the others. IMHO if we want to change this, we should do it for all of them. And `test_context` is basically already a fixture, so we should use it for this.

**Comment by snikulov** [comment]
@vadz Ok. Thank you. :)
I also find sqlcmd but need some time to check how it'll work. Will update my pull shortly.
Creating also good, but I suspect it can be server specific, and probably harder.

**Comment by snikulov** [comment]
@vadz I've closed this pull per your comments. New pr #415 submitted.
Now code is unchanged. Used sqlcmd for test preparation.

**Pull request closed without merging**
