### PR TITLE
Throwing an exception out of a destructor is forbidden

### PR DESCRIPTION
**Pull request by nefelim**
I faced application abort because of thrown exception in destructor.

### CODE REVIEW

**Comment by mloskot** [comment]
Sounds familiar https://github.com/SOCI/soci/pull/424#issuecomment-147404419
Please, have a look at the discussion to #256 and #257.

Please, provide a minimal example that shows how you call/use SOCI.

**Comment by snikulov** [comment]
@mloskot @msobczak Looks like @nefelim have found the dark corner of SOCI design about throwing exception from destructor :)
https://github.com/SOCI/soci/issues/256


@nefelim Looks at test results. Why do you think they broken?

**Comment by mloskot** [comment]
@snikulov Yes, so I suggested @nefelim to first familiarise himself with the archived discussion (which rooted with Roger Orr's message on the mailing list, https://sourceforge.net/p/soci/mailman/message/26451676/, also linked in that Issue comments).

Then, @nefelim can judge if he agrees or not, with SOCI design decisions. 
Perhaps, he found a new use case, apart from the convoluted one (https://github.com/SOCI/soci/issues/256#issuecomment-47965263) that we should consider.

Hence, I also asked @nefelim to provide better picture of what he is actually doing.

**Comment by snikulov** [comment]
@mloskot I think this one should be closed.

**Comment by nefelim** [comment]
I use SQLite3 db with "pragma foreign_key=ON" and has receive foreign key violation in case same is #256. Thank you for links.

**Pull request closed without merging**
