### PR TITLE
optional support for 64bit integer read in sqlite3 backend

### PR DESCRIPTION
**Pull request by mohansella**
Rationale discussed in #719

### CODE REVIEW

**Comment by vadz** [comment]
Sorry if I'm missing something, but isn't the compatibility breakage really bad here: i.e. do I understand correctly that this means that any existing code using `into(int_var)` will stop working and that there will be no way to fix it other than changing the variable type to `long long` (whether you need it or not)?

Also, from reading the code, it looks like int64 support should already work with SQLite if the column had been declared as "bigint" or "int8" when creating it, isn't it the case?

**Comment by mohansella** [comment]
Yes I can use bigint except.
1.for auto increment PK, only allowed is `INTEGER` which is my case.
2.reading an INTEGER type column with value greater than 32bit (e.g. epochmillis).

And also, I can realize what i am doing is wrong for the old code. So, I think, I should adjust the backend construct with option to change the default datatype without breaking the compatability.

**Comment by mohansella** [comment]
If the connection param is set as follows, we will get int64_t read in sqlite3.
`params.set_option("soci_sqlite3_integer_type", "dt_long_long");`

**Comment by mloskot** [comment]
@vadz apparetnly @mohansella has been nagging about merging this PR. What's the final conclusion?

**Comment by vadz** [comment]
Sorry, I don't even know what patches should be reviewed: there is #719, #720 and #721 (this one), should they all be applied together/sequentially or are some of them included in the other one(s)?

I'm travelling right now but I could review this next week when I get back.

**Comment by mohansella** [comment]
@vadz , sorry for the confusion. both the changes were merged into #720

**Pull request closed without merging**
