### PR TITLE
added test to demonstrate bug #221

### PR DESCRIPTION
**Pull request by hw-dwalter**

### CODE REVIEW

**Comment by snikulov** [comment]
@hw-dwalter well, you've expose issue with mysql and break all back-ends with syntax error.
< Cannot prepare statement. ERROR:  syntax error at or near "limit" >  - It seems to me not good for merge.
It should be either correct syntax for all back-ends, or specific test just for mysql.

**Comment by hw-dwalter** [comment]
I think the limit part can be removed. Should i make a new merge request?

**Comment by snikulov** [comment]
@hw-dwalter  Just update existing. Make changes and commit. Will see the result.

**Comment by snikulov** [comment]
@hw-dwalter Nice catch. Something wrong with Oracle tests.

<  ORA-01745: invalid host/bind variable name
   while executing "update soci_test set val = val + :increment where val = 5"
  with :increment=2. >

**Comment by snikulov** [comment]
@mloskot Can somebody with Oracle experience check this fail?

**Comment by hw-dwalter** [comment]
maybe we spotted another bug? as far as i understand this should work.

**Comment by snikulov** [comment]
@hw-dwalter Perhaps. That is why I've asked @mloskot to look. I have no Oracle in my environment to experiment :)

**Comment by mloskot** [comment]
Quick look at SQL `update soci_test set val = val + :increment where val = 5 with :increment=2` suggests, ORA-01745 may be thrown due to use of [Oracle reserved word](https://docs.oracle.com/cd/B19306_01/em.102/b40103/app_oracle_reserved_words.htm), namely `increment`.

**Comment by snikulov** [comment]
@hw-dwalter Can you change ```increment``` to ```step``` for example?

**Comment by snikulov** [comment]
:+1: LGTM. @hw-dwalter Could you please squash this change into single commit?

**Comment by mloskot** [comment]
Sweet, looks like Oracle has been fixed. Thx guys!

**Comment by snikulov** [comment]
@hw-dwalter Merged. Thank you.

**Comment by hw-dwalter** [comment]
thank you. but what about the fix for #221? should i make a new merge request?

**Comment by snikulov** [comment]
@hw-dwalter Yes. Since it has conflict, could you please re-submit it against latest master?

**Comment by hw-dwalter** [comment]
I resubmit this change after I reviewed it again. Because it is some years old.

**Comment by snikulov** [comment]
Agreed. Thank you.

**Pull request merged**
