### PR TITLE
core/statement.cpp : Modified to support complex queries

### PR DESCRIPTION
**Pull request by JoshuaVThomas**
Added a part where describe is called again if numcols doesn't get populated before execution of query.

Ref : https://github.com/SOCI/soci/issues/1151

### CODE REVIEW

**Comment by vadz** [comment]
Thanks, but it would be possible to add a test case that fails now but would work with this change? Otherwise this risks getting broken again in the future.

**Comment by vadz** [comment]
Sorry, I really can't merge without understanding what exactly this fixes.

**Comment by JoshuaVThomas** [comment]
Hi @vadz I've added the test case where this failed but succeeds now.

**Comment by vadz** [comment]
Thank you, but I'll need some help with understanding what exactly happens with this query... Any extra explanations would be welcome!

**Comment by JoshuaVThomas** [comment]
This is a sample query which has a CURSOR declared. It's aim is to execute a complex query at ones instead of set by set operation. Since it's a complex query it takes some time to execute so that the numcols doesn't get set. So the code has been modified to address this.

**Comment by vadz** [comment]
Sorry for the delay, I've finally looked at it and I couldn't find any better way to fix this than to apply _almost_ this change, please see #1182 which I've created to replace this one.

The main difference is that I don't understand how did it work for you, and even in the CI build, without calling `define_for_row()` after the 2nd `describe()`. In my local testing this just crashed because `intosForRow_` elements were never initialized and, again, I just don't see how could it work without it.

Anyhow, if you don't have any objections to calling `define_for_row()` too, I'll merge the other PR soon.

Thanks again for the fix!

**Pull request closed without merging**
