### PR TITLE
Sqlite3 optimization [#2]

### PR DESCRIPTION
**Pull request by ArnaudD-FR**
From PR #360 without dt_blob. This PR depends on PR #361

 * less conversions to/from string on binding/fetching
 * less temporary memory allocations
 * better timing on insert/select.

In the following table are presented timing in milliseconds for action on 1 million of rows (see source code below table). Sqlite3 API column is just here to give an idea of soci overhead time on same requests when possible.

Action                                          |SOCI (master) |     SOCI (+ optim)   |   sqlite3 APIs
------------------------------------------------|--------------|-----------------------------|--------------------
[int][INSERT]                                   | 7837         | 7534        | 5773
[int][INSERT] with statement          |  2035        |  1819     |   1589
[int][SELECT] with statement          |   370        |   206     |    124
[vector<int>][INSERT] insert          |  1988        |  1747     |   
[vector<int>][SELECT]                 |   603    |   226     |   
[double][INSERT]                      |  9650    |  8314     |   5624
[double][INSERT] with statement insert|  3090    |  1859     |   1577
[double][SELECT] with statement       |   644    |   213     |    131
[vector<double>][INSERT]              |  2718    |  1789     |   
[vector<double>][SELECT]              |   590    |   232     |   
[string][INSERT]                      |  7730    |  7637     |   6012
[string][INSERT] with statement       |  2034    |  1757     |   1754
[string][SELECT] with statement       |   364    |   265     |    191
[vector<string>][INSERT]              |  2232    |  1750     |   
[vector<string>][SELECT]              |   476    |   360     |   
[FOOBAR][INSERT] foo insert           |  2529    |  1931     |   1876
[FOOBAR][INSERT] bar insert           |  2935    |  2402     |   2334
[FOOBAR][SELECT] join                 |  1833    |  1497     |   1164
[FOOBAR][SELECT] filter on bar        |  8085    |  6019     |   4835

```c++
#include <soci/soci.h>
#include <chrono>

#include <iostream>
#include <sqlite3.h>

typedef std::chrono::system_clock _clock;

int duration(const _clock::time_point &begin, const _clock::time_point &end = _clock::now())
{
    return std::chrono::duration_cast<std::chrono::milliseconds>(end - begin).count();
}

#define NB_INSERT 1000000

void soci_tests()
{
    std::cout << "SOCI tests" << std::endl;

    soci::session db("sqlite3", ":memory:");

    db << "CREATE TABLE test("
            "a INTEGER,"
            "b TEXT,"
            "c DOUBLE"
          ")";

    // insert
    {
        _clock::time_point b = _clock::now();
        for (int i = 0; i < NB_INSERT; ++i)
            db << "INSERT INTO test(a) VALUES(?)", soci::use(i);
        std::cout << "\t[int][INSERT] duration: " << duration(b) << std::endl;
    }

    db << "DELETE FROM test";

    {
        _clock::time_point b = _clock::now();
        int i;
        soci::statement stmt = (db.prepare << "INSERT INTO test(a) VALUES(?)", soci::use(i));
        for (i = 0; i < NB_INSERT; ++i)
            stmt.execute(true);
        std::cout << "\t[int][INSERT] with statement duration: " << duration(b) << std::endl;

        b = _clock::now();
        soci::statement stmt2 = (db.prepare << "SELECT a FROM test", soci::into(i));
        stmt2.execute(false);
        while(stmt2.fetch())
            ;
        std::cout << "\t[int][SELECT] with statement duration: " << duration(b) << std::endl;
    }
    db << "DELETE FROM test";

    {
        _clock::time_point b = _clock::now();
        std::vector<int> vi(NB_INSERT);
        for (int i = 0; i < NB_INSERT; ++i)
            vi[i] = i;
        db << "INSERT INTO test(a) VALUES(?)", soci::use(vi);
        std::cout << "\t[vector<int>][INSERT] insert duration: " << duration(b) << std::endl;

        b = _clock::now();
        db << "SELECT a FROM test", soci::into(vi);
        std::cout << "\t[vector<int>][SELECT] duration: " << duration(b) << std::endl;

    }
    db << "DELETE FROM test";


    {
        _clock::time_point b = _clock::now();
        for (double d = 0; d < NB_INSERT/10; d=d+0.1)
            db << "INSERT INTO test(c) VALUES(?)", soci::use(d);
        std::cout << "\t[double][INSERT] duration: " << duration(b) << std::endl;
    }
    db << "DELETE FROM test";

    {
        _clock::time_point b = _clock::now();
        double d;
        soci::statement stmt = (db.prepare << "INSERT INTO test(c) VALUES(?)", soci::use(d));
        for (d = 0; d < NB_INSERT/10; d=d+0.1)
            stmt.execute(true);
        std::cout << "\t[double][INSERT] with statement insert duration: " << duration(b) << std::endl;

        b = _clock::now();
        soci::statement stmt2 = (db.prepare << "SELECT c FROM test", soci::into(d));
        stmt2.execute(false);
        while(stmt2.fetch())
            ;
        std::cout << "\t[double][SELECT] with statement duration: " << duration(b) << std::endl;
    }
    db << "DELETE FROM test";

    {
        _clock::time_point b = _clock::now();
        std::vector<double> vd(NB_INSERT);
        for (int i = 0; i < NB_INSERT; ++i)
            vd[i] = ((double)(i))/10;
        db << "INSERT INTO test(c) VALUES(?)", soci::use(vd);
        std::cout << "\t[vector<double>][INSERT] duration: " << duration(b) << std::endl;

        b = _clock::now();
        db << "SELECT c FROM test", soci::into(vd);
        std::cout << "\t[vector<double>][SELECT] duration: " << duration(b) << std::endl;
    }
    db << "DELETE FROM test";

    {
        _clock::time_point b = _clock::now();
        std::string test = "abcdefghijklmnopqrstuvxyzABCDEFGHIJKLMNOPQRSTUVXYZ0123456789";
        for (int i = 0; i < NB_INSERT; ++i)
        {
            test[i%test.size()] = 'a'+(i%25);
            db << "INSERT INTO test(b) VALUES(?)", soci::use(test);
        }
        std::cout << "\t[string][INSERT] duration: " << duration(b) << std::endl;
    }
    db << "DELETE FROM test";

    {
        _clock::time_point b = _clock::now();
        std::string test = "abcdefghijklmnopqrstuvxyzABCDEFGHIJKLMNOPQRSTUVXYZ0123456789";
        soci::statement stmt = (db.prepare << "INSERT INTO test(b) VALUES(?)", soci::use(test));
        for (int i = 0; i < NB_INSERT; ++i)
        {
            test[i%test.size()] = 'a'+(i%25);
            stmt.execute(true);
        }
        std::cout << "\t[string][INSERT] with statement duration: " << duration(b) << std::endl;

        b = _clock::now();
        soci::statement stmt2 = (db.prepare << "SELECT b FROM test", soci::into(test));
        stmt2.execute(false);
        while(stmt2.fetch())
            ;
        std::cout << "\t[string][SELECT] with statement duration: " << duration(b) << std::endl;

    }
    db << "DELETE FROM test";

    {
        _clock::time_point b = _clock::now();
        std::vector<std::string> vs(NB_INSERT);
        for (int i = 0; i < NB_INSERT; ++i)
        {
            vs[i] = "abcdefghijklmnopqrstuvxyzABCDEFGHIJKLMNOPQRSTUVXYZ0123456789";
            vs[i][i%vs[i].size()] = 'a'+(i%25);
        }
        db << "INSERT INTO test(b) VALUES(?)", soci::use(vs);
        std::cout << "\t[vector<string>][INSERT] duration: " << duration(b) << std::endl;

        b = _clock::now();
        db << "SELECT b FROM test", soci::into(vs);
        std::cout << "\t[vector<string>][SELECT] duration: " << duration(b) << std::endl;
    }
    db << "DELETE FROM test";

    db << "CREATE TABLE foo(a INTEGER PRIMARY KEY, a_str TEXT NOT NULL)";
    db << "CREATE TABLE bar(b INTEGER REFERENCES foo(a), b_str TEXT NOT NULL)";
    db << "PRAGMA foreign_keys = ON";

    // initialize foo
    {
        int a = 0;
        std::string as;
        char astr[100];

        _clock::time_point b = _clock::now();
        soci::statement stmt = (db.prepare << "INSERT INTO foo(a, a_str) VALUES(?,?)", soci::use(a), soci::use(as));

        for (int i = 0; i < NB_INSERT; ++i)
        {
            a = i;
            snprintf(astr, sizeof(astr), "%i", i);
            as = astr;
            stmt.execute(true);
        }

        std::cout << "\t[FOOBAR][INSERT] foo insert duration: " << duration(b) << std::endl;
    }

    {
        int b = 0;
        std::string bs;
        char bstr[100];

        _clock::time_point begin = _clock::now();
        soci::statement stmt = (db.prepare << "INSERT INTO bar(b, b_str) VALUES(?,?)", soci::use(b), soci::use(bs));

        for (int i = 0; i < NB_INSERT; ++i)
        {
            b = i%100;
            snprintf(bstr, sizeof(bstr), "%i", i);
            bs = bstr;
            stmt.execute(true);
        }

        std::cout << "\t[FOOBAR][INSERT] bar insert duration: " << duration(begin) << std::endl;
    }

    {
        int a;
        std::string as;
        int b;
        std::string bs;

        _clock::time_point begin = _clock::now();
        soci::statement stmt = (db.prepare << "SELECT a, a_str, b, b_str FROM foo JOIN bar ON a = b ORDER BY a", soci::into(a), soci::into(as), soci::into(b), soci::into(bs));

        stmt.execute(false);
        while (stmt.fetch())
            ;

        std::cout << "\t[FOOBAR][SELECT] join duration: " << duration(begin) << std::endl;
    }

    {
        int b;
        std::string bs;


        _clock::time_point begin = _clock::now();
        for (int i = 0; i < 100; ++i)
        {
            b = i;
            soci::statement stmt = (db.prepare << "SELECT b_str FROM bar WHERE b = ?", soci::use(b), soci::into(b));
            stmt.execute(false);
            while (stmt.fetch())
                ;

        }
        std::cout << "\t[FOOBAR][SELECT] filter on bar duration: " << duration(begin) << std::endl;
    }

    db << "DROP TABLE bar";
    db << "DROP TABLE foo";
}

void sqlite3_tests()
{
    std::cout << "SQLITE3 tests" << std::endl;
    sqlite3 *db;

#define CHECK_SQLITE_ST(fct, st)   \
    if (fct != st)   \
    {                       \
        std::cout << "Failed to execute function at line " << __LINE__ << std::endl;  \
        sqlite3_close_v2(db);   \
        return;     \
    }

#define CHECK_SQLITE(fct)   CHECK_SQLITE_ST(fct, SQLITE_OK)

#define CHECK(a, b) \
    if ((a) != (b)) \
    {   \
        std::cout << "Check failed at line " << __LINE__ << ": " << (a) << " != " << (b) << std::endl;  \
        sqlite3_close_v2(db);   \
        return;     \
    }

    CHECK_SQLITE(sqlite3_open_v2(":memory:", &db, SQLITE_OPEN_READWRITE | SQLITE_OPEN_CREATE, NULL))

    {
        sqlite3_stmt *stmt;
        CHECK_SQLITE(sqlite3_prepare_v2(db, "CREATE TABLE test(a INTEGER, b TEXT, c DOUBLE)", -1, &stmt, NULL));
        CHECK_SQLITE_ST(sqlite3_step(stmt), SQLITE_DONE);
        CHECK_SQLITE(sqlite3_finalize(stmt));
    }

    {
        _clock::time_point b = _clock::now();
        for (int i = 0; i < NB_INSERT; ++i)
        {
            sqlite3_stmt *stmt;
            CHECK_SQLITE(sqlite3_prepare_v2(db, "INSERT INTO test(a) VALUES(?)", -1, &stmt, NULL));
            CHECK_SQLITE(sqlite3_bind_int(stmt, 1, i));
            CHECK_SQLITE_ST(sqlite3_step(stmt), SQLITE_DONE);
            CHECK_SQLITE(sqlite3_finalize(stmt));
        }
        std::cout << "\t[int][INSERT] duration: " << duration(b) << std::endl;
    }

    CHECK_SQLITE(sqlite3_exec(db, "DELETE FROM test", NULL, NULL, NULL));

    {
        _clock::time_point b = _clock::now();
        sqlite3_stmt *stmt;
        CHECK_SQLITE(sqlite3_prepare_v2(db, "INSERT INTO test(a) VALUES(?)", -1, &stmt, NULL));
        for (int i = 0; i < NB_INSERT; ++i)
        {
            CHECK_SQLITE(sqlite3_bind_int(stmt, 1, i));
            CHECK_SQLITE_ST(sqlite3_step(stmt), SQLITE_DONE);
            CHECK_SQLITE(sqlite3_reset(stmt));
        }
        CHECK_SQLITE(sqlite3_finalize(stmt));
        std::cout << "\t[int][INSERT] with statement duration: " << duration(b) << std::endl;

        b = _clock::now();
        CHECK_SQLITE(sqlite3_prepare_v2(db, "SELECT a FROM test", -1, &stmt, NULL));
        int i = 0;
        while (sqlite3_step(stmt) == SQLITE_ROW)
        {
            i = sqlite3_column_int(stmt, 0);
        }
        CHECK(i, NB_INSERT-1);
        CHECK_SQLITE(sqlite3_finalize(stmt));
        std::cout << "\t[int][SELECT] with statement duration: " << duration(b) << std::endl;
    }
    CHECK_SQLITE(sqlite3_exec(db, "DELETE FROM test", NULL, NULL, NULL));

    {
        _clock::time_point b = _clock::now();
        for (double d = 0; d < NB_INSERT/10; d=d+0.1)
        {
            sqlite3_stmt *stmt;
            CHECK_SQLITE(sqlite3_prepare_v2(db, "INSERT INTO test(c) VALUES(?)", -1, &stmt, NULL));
            CHECK_SQLITE(sqlite3_bind_double(stmt, 1, d));
            CHECK_SQLITE_ST(sqlite3_step(stmt), SQLITE_DONE);
            CHECK_SQLITE(sqlite3_finalize(stmt));
        }
        std::cout << "\t[double][INSERT] duration: " << duration(b) << std::endl;
    }
    CHECK_SQLITE(sqlite3_exec(db, "DELETE FROM test", NULL, NULL, NULL));

    {
        _clock::time_point b = _clock::now();
        double d;
        sqlite3_stmt *stmt;
        CHECK_SQLITE(sqlite3_prepare_v2(db, "INSERT INTO test(c) VALUES(?)", -1, &stmt, NULL));
        for (d = 0; d < NB_INSERT/10; d=d+0.1)
        {
            CHECK_SQLITE(sqlite3_bind_double(stmt, 1, d));
            CHECK_SQLITE_ST(sqlite3_step(stmt), SQLITE_DONE);
            CHECK_SQLITE(sqlite3_reset(stmt));
        }
        CHECK_SQLITE(sqlite3_finalize(stmt));
        std::cout << "\t[double][INSERT] with statement insert duration: " << duration(b) << std::endl;

        b = _clock::now();
        CHECK_SQLITE(sqlite3_prepare_v2(db, "SELECT c FROM test", -1, &stmt, NULL));
        d = 0;
        while (sqlite3_step(stmt) == SQLITE_ROW)
        {
            d = sqlite3_column_double(stmt, 0);
        }
        CHECK_SQLITE(sqlite3_finalize(stmt));
        CHECK((int)(d*10), NB_INSERT-1);
        std::cout << "\t[double][SELECT] with statement duration: " << duration(b) << std::endl;
    }
    CHECK_SQLITE(sqlite3_exec(db, "DELETE FROM test", NULL, NULL, NULL));

    {
        _clock::time_point b = _clock::now();
        std::string test = "abcdefghijklmnopqrstuvxyzABCDEFGHIJKLMNOPQRSTUVXYZ0123456789";
        for (int i = 0; i < NB_INSERT; ++i)
        {
            test[i%test.size()] = 'a'+(i%25);

            sqlite3_stmt *stmt;
            CHECK_SQLITE(sqlite3_prepare_v2(db, "INSERT INTO test(b) VALUES(?)", -1, &stmt, NULL));
            CHECK_SQLITE(sqlite3_bind_text(stmt, 1, test.c_str(), test.size(), NULL));
            CHECK_SQLITE_ST(sqlite3_step(stmt), SQLITE_DONE);
            CHECK_SQLITE(sqlite3_finalize(stmt));
        }
        std::cout << "\t[string][INSERT] duration: " << duration(b) << std::endl;
    }
    CHECK_SQLITE(sqlite3_exec(db, "DELETE FROM test", NULL, NULL, NULL));

    {
        _clock::time_point b = _clock::now();
        std::string test = "abcdefghijklmnopqrstuvxyzABCDEFGHIJKLMNOPQRSTUVXYZ0123456789";
        sqlite3_stmt *stmt;
        CHECK_SQLITE(sqlite3_prepare_v2(db, "INSERT INTO test(b) VALUES(?)", -1, &stmt, NULL));
        for (int i = 0; i < NB_INSERT; ++i)
        {
            test[i%test.size()] = 'a'+(i%25);
            CHECK_SQLITE(sqlite3_bind_text(stmt, 1, test.c_str(), test.size(), NULL));
            CHECK_SQLITE_ST(sqlite3_step(stmt), SQLITE_DONE);
            CHECK_SQLITE(sqlite3_reset(stmt));
        }
        CHECK_SQLITE(sqlite3_finalize(stmt));
        std::cout << "\t[string][INSERT] with statement duration: " << duration(b) << std::endl;

        b = _clock::now();
        CHECK_SQLITE(sqlite3_prepare_v2(db, "SELECT b FROM test", -1, &stmt, NULL));
        int i = 0;
        std::string s;
        while (sqlite3_step(stmt) == SQLITE_ROW)
        {
            s = (const char *)sqlite3_column_text(stmt, 0);
            ++i;
        }
        CHECK_SQLITE(sqlite3_finalize(stmt));
        CHECK(i, NB_INSERT);
        std::cout << "\t[string][SELECT] with statement duration: " << duration(b) << std::endl;

    }
    CHECK_SQLITE(sqlite3_exec(db, "DELETE FROM test", NULL, NULL, NULL));

    CHECK_SQLITE(sqlite3_exec(db, "CREATE TABLE foo(a INTEGER PRIMARY KEY, a_str TEXT NOT NULL)", NULL, NULL, NULL));
    CHECK_SQLITE(sqlite3_exec(db, "CREATE TABLE bar(b INTEGER REFERENCES foo(a), b_str TEXT NOT NULL)", NULL, NULL, NULL));
    CHECK_SQLITE(sqlite3_exec(db, "PRAGMA foreign_keys = ON", NULL, NULL, NULL));

    // initialize foo
    {
        int a = 0;
        std::string as;
        char astr[100];

        _clock::time_point b = _clock::now();

        sqlite3_stmt *stmt;
        CHECK_SQLITE(sqlite3_prepare_v2(db, "INSERT INTO foo(a, a_str) VALUES(?,?)", -1, &stmt, NULL));

        for (int i = 0; i < NB_INSERT; ++i)
        {
            a = i;
            snprintf(astr, sizeof(astr), "%i", i);
            as = astr;
            CHECK_SQLITE(sqlite3_bind_int(stmt, 1, a));
            CHECK_SQLITE(sqlite3_bind_text(stmt, 2, as.c_str(), as.size(), NULL));
            CHECK_SQLITE_ST(sqlite3_step(stmt), SQLITE_DONE);
            CHECK_SQLITE(sqlite3_reset(stmt));
        }
        CHECK_SQLITE(sqlite3_finalize(stmt));

        std::cout << "\t[FOOBAR][INSERT] foo insert duration: " << duration(b) << std::endl;
    }

    {
        int b = 0;
        std::string bs;
        char bstr[100];

        _clock::time_point begin = _clock::now();

        sqlite3_stmt *stmt;
        CHECK_SQLITE(sqlite3_prepare_v2(db, "INSERT INTO bar(b, b_str) VALUES(?,?)", -1, &stmt, NULL));

        for (int i = 0; i < NB_INSERT; ++i)
        {
            b = i%100;
            snprintf(bstr, sizeof(bstr), "%i", i);
            bs = bstr;
            CHECK_SQLITE(sqlite3_bind_int(stmt, 1, b));
            CHECK_SQLITE(sqlite3_bind_text(stmt, 2, bs.c_str(), bs.size(), NULL));
            CHECK_SQLITE_ST(sqlite3_step(stmt), SQLITE_DONE);
            CHECK_SQLITE(sqlite3_reset(stmt));
        }
        CHECK_SQLITE(sqlite3_finalize(stmt));

        std::cout << "\t[FOOBAR][INSERT] bar insert duration: " << duration(begin) << std::endl;
    }

    {
        int a;
        std::string as;
        int b;
        std::string bs;

        _clock::time_point begin = _clock::now();

        sqlite3_stmt *stmt;
        CHECK_SQLITE(sqlite3_prepare_v2(db, "SELECT a, a_str, b, b_str FROM foo JOIN bar ON a = b ORDER BY a", -1, &stmt, NULL));

        while (sqlite3_step(stmt) == SQLITE_ROW)
        {
            a = sqlite3_column_int(stmt, 0);
            as = (const char *)sqlite3_column_text(stmt, 1);
            b = sqlite3_column_int(stmt, 2);
            bs = (const char *)sqlite3_column_text(stmt, 3);
        }
        CHECK_SQLITE(sqlite3_finalize(stmt));

        std::cout << "\t[FOOBAR][SELECT] join duration: " << duration(begin) << std::endl;
    }

    {
        int b;
        std::string bs;

        _clock::time_point begin = _clock::now();
        for (int i = 0; i < 100; ++i)
        {
            b = i;
            sqlite3_stmt *stmt;
            CHECK_SQLITE(sqlite3_prepare_v2(db, "SELECT b_str FROM bar WHERE b = ?", -1, &stmt, NULL));
            while (sqlite3_step(stmt) == SQLITE_ROW)
            {
                b = sqlite3_column_int(stmt, 0);
                bs = (const char *)sqlite3_column_text(stmt, 1);
            }
            CHECK_SQLITE(sqlite3_finalize(stmt));

        }
        std::cout << "\t[FOOBAR][SELECT] filter on bar duration: " << duration(begin) << std::endl;
    }

    CHECK_SQLITE(sqlite3_exec(db, "DROP TABLE bar", NULL, NULL, NULL));
    CHECK_SQLITE(sqlite3_exec(db, "DROP TABLE foo", NULL, NULL, NULL));

    sqlite3_close_v2(db);
}

int main()
{
    soci_tests();
    sqlite3_tests();
    return 0;
}
```

### CODE REVIEW

**Comment by vadz** [comment]
I don't have any real comments about this, but then I don't know much about SQLite API anyhow, so it would be nice if someone who did could review this. If nobody does, I'll probably go ahead and commit this in a few days, thanks!

**Comment by mloskot** [comment]
No showstoppers, but general comments:
* I'm not SQLite guru, so I can't judge if there are any major issues.
* It doesn't break anything, but it seems to speed up things, so it's great!
* It seems, there is number of indentation changes w/o changes in code, especially in switch/case statements. It's not easy to review, to filter out what's actually new there. Next time, if you aim for formatting clean up, please do it in separate commits, preferably in separate PRs.
* Similarly, warnings and memory leaks should be cleaned up in separate PRs - we use git, so even PR with single line change deserves a separate topic branches.

:+1: for merging. 
Thanks @ArnaudD-FR !

**Comment by ArnaudD-FR** [comment]
- Hum, usually I don't change indent when not necessary, but yes there is a lot of switch/case that have been totally rewritten. I believe the diff tool is a little bit lost.
 - I pushed warning and memory leaks to this PR as there were introduced by this PR and it was not yet closed. Wrong idea?

This PR require #361, but I have some remaining job to do on #361.

**Comment by mloskot** [comment]
Re memory leak, OK, I understand it now.
The switch cases seem to have been cleaned up, reordered and reformatted by the way of changing them. It is OK, but perhaps separate commit would make it clearer.

Let us know whenever you are ready, so we merge this PR.

**Comment by ArnaudD-FR** [comment]
I've rebased on master since PR #361 has been merged and squashed the 2 last commits inside "sqlite3 backend optimizations" as it was related.

Nothing more to be updated ton this PR

**Comment by mloskot** [comment]
Great.If @vadz  doesn't merge within a day or two, I will do it. Thanks!

**Comment by mloskot** [comment]
Thank you

**Pull request merged**
