### PR TITLE
[Build] The -Werror flag is enabled only for Debug builds - issue #812

### PR DESCRIPTION
**Pull request by denisarnaud**
See also #813 and #812

### CODE REVIEW

**Comment by denisarnaud** [comment]
That change allows to cleanly build on ARMv7hl: https://koji.fedoraproject.org/koji/taskinfo?taskID=45426720
So, awaiting for your accepting to merge that pull request :)

**Comment by vadz** [comment]
I'd really like to modify Travis/Appveyor configs to enable using `-Werror`, we still want to do it there. If you could do it, it would be great, otherwise I'll try to do it later but, as I said, not immediately.

**Comment by denisarnaud** [comment]
> I'd really like to modify Travis/Appveyor configs to enable using `-Werror`, we still want to do it there. If you could do it, it would be great, otherwise I'll try to do it later but, as I said, not immediately.

If you build in Debug mode (`-DCMAKE_BUILD_TYPE=Debug`)), `-Werror` will be activated by default. And Debug mode makes sense for CI (at least to me). I know how to configure Travis CI, but not (yet) AppVeyor.

**Comment by vadz** [comment]
No, sorry, I disagree. We really want to run the tests using the production version, because this is what we ultimately care about. If some optimization breaks something in SOCI (which is not impossible), we want to know about it.

**Comment by denisarnaud** [comment]
> No, sorry, I disagree. We really want to run the tests using the production version, because this is what we ultimately care about. If some optimization breaks something in SOCI (which is not impossible), we want to know about it.

You are absolutely right in principle (and I actually fully subscribe to such principle myself: https://www.12factor.net/dev-prod-parity). Normally, with CI tools, it's pretty straightforward to test several configurations in parallel. In Travis CI, for instance, one test per line in the `env:` section is made. So, we can have `-DCMAKE_BUILD_TYPE=Debug` and `-DCMAKE_BUILD_TYPE=Release` kind of rows (out of my memory; there are surely other ways to that properly).

**Comment by vadz** [comment]
I'd really prefer to keep things simple and just pass extra `CXXFLAGS` to the build. I'm completely CMake ignorant so I always forget how to do it, but surely this must be possible.

**Comment by denisarnaud** [comment]
Ok, no problem, I'm with you: 5afc2f54a3454f06c1001b13603054f74d4d16ab
If, in the `cmake` command-line, you pass the `-DSOCI_ENABLE_WERROR=ON` option, `-Werror` will appear where it used to appear. By default, `-Werror` does not appear.

**Comment by vadz** [comment]
Sorry for the delay, I've finally returned to this and made the changes to keep using `-Werror` in the CI builds in #825, so I'm closing this one in favour of the other PR which I'll merge as soon as the CI builds there finish successfully.

**Pull request closed without merging**
