### PR TITLE
Add explicit qualifier to mssql odbc testcase

### PR DESCRIPTION
**Pull request by hrabe**
Fixes https://github.com/SOCI/soci/issues/648

### CODE REVIEW

**Comment by vadz** [comment]
Thanks for fixing this!

**Comment by mloskot** [comment]
@vadz Please, set the *4.0.0* milestone for every PR you merge. At least for those you merge before we finally release 4.0.0. This is a small tick, but will help greatly to collect release notes. Thanks.

**Comment by vadz** [comment]
Sorry, I didn't know/forgot about this. FWIW I don't think we should mention compilation fixes for the tests in the release notes anyhow because it's implicitly understood that tests should compile anyhow, but I'll do it for any other changes/fixes in the future.

**Comment by mloskot** [comment]
@vadz 
> I don't think we should mention compilation fixes for the tests in the release notes anyhow

Indeed, and we won't.

I just simplify the procedure:
- milestone everything, no-brainer
- dump everything for a milestone
- sieving dump keeping the important bits only

Otherwise, I'd have to ask myself if I have perhaps missed milestone-ing something important.

**Comment by vadz** [comment]
@mloskot I usually look at `git log --oneline the_last_release_tag..` when preparing the release notes. Maybe we could use some tags (e.g. `[change]` or something like this) in the commit messages to simplify this?

**Comment by mloskot** [comment]
@vadz I used to do something similar, as outlined here https://github.com/SOCI/soci/issues/93#issuecomment-15434667

I'm not sure about a commit tag, easier to forget than single milestone click (which also works for issues about future fixes/features).

Ideally, if a PR merge is accompanied with entry in `CHANGES` file, then we have it covered and no need to spend hours filtering logs to compile release notes :)

**Comment by vadz** [comment]
@mloskot This would work too, but for the projects which keep a running changelog like this, another problem is common: merge conflicts for any change touching the changelog (which will be most of them). For SOCI this might not be such a big deal though, as we don't get that many PRs... but it's annoying.

**Comment by mloskot** [comment]
@vadz Good point. I see no golden solution. Feel free to suggest one, we can try.

**Pull request merged**
