### PR TITLE
Fixing uninitialized gotData_ in soci::statement #609

### PR DESCRIPTION
**Pull request by AngelinNjakasoa**
This fixes the uninitialized gotData_ in constructors and copy assignment operator of the class
soci::statement.

### CODE REVIEW

**Comment by vadz** [comment]
Thanks for the changes, but I'm not quite sure what the actual semantics of `gotData_` is, i.e. do we really expect `got_data()` to return true on a new copy of the statement? If so, I wonder why isn't `gotData_` a member of `statement_impl` rather than `statement` itself in the first place?

Anyhow, I don't see any problem with applying this, but `statement` copy ctor should initialize it too then, presumably. And if we can move it to `statement_impl`, this would arguably be even better.

**Comment by mloskot** [comment]
@AngelinNjakasoa would you be willing to refine your PR as per @vadz comment?
Then it will have a chance to make it into 4.0.0 release - I'm not able myself to work on updating your PR now.

**Comment by mloskot** [comment]
Apparently OP has got lost in action and to move forward I'm going to accept this PR as is.
Next, I will add the missing initialisation to the `statement` copy ctor.

Rest of the suggestions of improvements will have to wait.

**Comment by mloskot** [comment]
B***dy hell I should have squashed the commits. I completely forgot PR update via GitHub generates those silly `Merge branch 'master' into master`. Sorry!

**Pull request merged**
