### PR TITLE
fixing bug with boost::optional and explicit null indicator passed to use()

### PR DESCRIPTION
**Pull request by ddurham2**
Fixes issue #802

The issue explains the need.

The first unit test demonstrates the main problem if the fix is not in place.
The second unit test demonstrates the problem if the fix didn't compare with the address of &ownInd_

### CODE REVIEW

**Comment by ddurham2** [comment]
@vadz, I completed my PR for this bug.  Everything passes except the db2, odbc and oracle backends.  

But, they're failing on my second unit test (which I only added to demonstrate the internal need for the check against &ownInd_ which we discussed).  So, I can only imagine that this means that those backends are for some reason modifying the indicator's value on INSERT which is mutating the value of ownInd_ which is supposed to stay the same since a prepared statement may execute multiple times (and that this second test would have failed with or without my actual fix).

I don't have these backends to try and troubleshoot.  Do you?  Otherwise, I can only try to track down the problem by just submitting various commits for travis to run and get it to log things.

**Comment by vadz** [comment]
Yes, I definitely will have to look at this as we use ODBC and Oracle backends (and DB/2 is the same as ODBC anyhow, mostly). I'll try to debug this a.s.a.p. (but this might not be very soon in clock time...), thanks for the tests!

**Comment by vadz** [comment]
I've finally fixed the bug in the ODBC backend, see 3d39f7a88fcb761ab3b4bbdf60f124aed29a546b which is currently getting tested as part of #870. If the CI builds there pass, and if you don't have any objections to my changes there done on top of your commits, I'm going to merge that PR.

Thanks again!

**Comment by ddurham2** [comment]
Sure, not problem.  Just so long as the unit tests I added are incorporated and do pass, then we should be fine on this end.
Thanks!

**Pull request closed without merging**
