### PR TITLE
Fix issue #349 Mysql backend memory leaks due to mysql_library_init()

### PR DESCRIPTION
**Pull request by thibault-martinez**
See issue #349

### CODE REVIEW

**Comment by vadz** [comment]
I don't know much about MySQL, but is this really correct if there is more than one connection alive? I would naively expect that `mysql_library_end()` should only be called when there are no more of them left...

**Comment by thibault-martinez** [comment]
I think you're right, only the last remaining mysql backend should call `mysql_library_end()`...
Is there any way to know if other backends are still working ?

**Comment by mloskot** [comment]
@thibault-martinez
> Do you have any internal way to know if other backends are still alive ?

There is no way to know it.
We can't use `std::atomic` we still support pre-C++11 compilers.
A counter internally  managed by `mysql_session_backend` sounds like a good choice.
However, it needs to take the [connection_pool](http://soci.sourceforge.net/doc/3.2/multithreading.html) use cases into account.

**Comment by b1c9g76** [comment]
I saw that on high volume use this log message was appearing with this patch:

Error in my_thread_global_end(): 2 threads didn't exit

**Comment by vadz** [comment]
I'm finally going to merge this, better late than never and all this. Thanks!

**Comment by vadz** [comment]
Merged as 78c5a313 (not sure why GitHub didn't notice this automatically), thanks again!

**Pull request closed without merging**
