### PR TITLE
Add -Wl,-flat_namespace -Wl,-undefined -Wl,suppress to LINK_FLAGS on Apple/OSX

### PR DESCRIPTION
**Pull request by mloskot**
Addresses compilation issues on OSX, see #258 and dup #334

### CODE REVIEW

**Comment by OniDaito** [comment]
Happy to take a look. I've been working a little with the OSX version.

**Comment by dunn** [comment]
Still failing to build; can't locate `error.h`:
- [GCC](https://gist.github.com/dunn/33401f01716951288e84)
- [Clang](https://gist.github.com/dunn/b7cddcecc45f54f3c97c)

**Comment by mloskot** [comment]
Can you erase line `#include "error.h"` in `src/backends/sqlite3/error.cpp` and check if it builds?

It seems like a bug indeed, becasue there is no `error.h` header specific to the SQLite3 backend.

It is unclear, why this issue didn't leak earlier, on Linux for instance.
*  There is only public header `include/soci/error.h` which, if used, should be included usnig qualified path `#include <soci/error.h>`, it this header is not required in SQLite3.
* Another possibility is that `include/soci/error.h` is unexpectadely included  due to misconfigured `-I` paths, but as I see [in this log](https://gist.githubusercontent.com/dunn/33401f01716951288e84/raw/89fa77d7bf1e90b258c0fb610be2f8474d429754/02.make) for example, this is not the case:
```
-I/tmp/soci20150518-44411-1tywz1v
-I/tmp/soci20150518-44411-1tywz1v/include
-I/tmp/soci20150518-44411-1tywz1v/include/private
```
there is no `-I/tmp/soci20150518-44411-1tywz1v/include/soci`

Regardless, AFAIS, `#include "error.h"` is not necessary in `src/backends/sqlite3/error.cpp`.

**Comment by mloskot** [comment]
It sesems the mystery behind successful builds on Linux has been solved: `#include "error.h"` directive in `src/backends/sqlite3/error.cpp` was including the GNU C Library `/usr/include/error.h`.

**Comment by dunn** [comment]
New errors!
- [Clang](https://gist.github.com/dunn/662fc0a002fa59d84cd5#file-02-make-L372)
- [GCC](https://gist.github.com/dunn/aebed168a9c14ed3ac44#file-02-make-L374)

**Comment by mloskot** [comment]
Apparently, there is names conflict between 
```
using namespace soci;
session sql;
```
and `struct session` defined in `/usr/include/sys/proc.h` on OSX.

@vadz You don't happen to have OSX to confirm that? Shall we `soci::` qualify names in tests?

**Comment by vadz** [comment]
Qualifying names with `soci::` would definitely work but would be rather ugly, it would be nice if things could be made to work without it. I wonder where is `sys/proc.h` get included from and if there is any way to avoid it (`gcc -H` could be used to discover it).

**Comment by mloskot** [comment]
I think [the logs](https://gist.github.com/dunn/aebed168a9c14ed3ac44#file-02-make-L374) we've already got pin-point source:
```
In file included from /usr/include/sys/sysctl.h:84:0,
                 from /tmp/soci20150518-55914-sm7vru/tests/catch.hpp:6752,
                 from /tmp/soci20150518-55914-sm7vru/tests/empty/test-empty.cpp:14:
/usr/include/sys/proc.h:82:8: note: candidates are: struct session
 struct session;
        ^
```

**Comment by vadz** [comment]
Ah, thanks, I didn't notice this.

Unfortunately now that we know where it is included from, I still have no idea how to fix it, the obverse face of having a header-only library is that anything used in its implementation also pollutes the global namespace and this is exactly what happens here.

The only horrible hack I see is to

    // Avoid problems with "session" being defined in sys/proc.h (indirectly) included by CATCH under OS X
    #define session session_system
    #include "catch.hpp"
    #undef session

but I'm not really sure if it's less ugly than using `soci::` everywhere...

**Comment by mloskot** [comment]
@vadz I'd simply replace `session` with `soci::session`. I can do it tonight.

**Comment by mloskot** [comment]
@dunn Could you give #341 patch a try and see if it solves the problems for you?

**Pull request merged**
